# CORREÇÃO DEFINITIVA - Backend Services
# Configuração otimizada para funcionar imediatamente

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-fixed
  namespace: direito-lux-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-fixed
  template:
    metadata:
      labels:
        app: auth-service-fixed
    spec:
      containers:
      - name: auth-service
        image: us-central1-docker.pkg.dev/direito-lux-staging-2025/direito-lux-staging/auth-service:latest
        ports:
        - containerPort: 8080
        env:
        # Database config
        - name: DB_HOST
          value: "postgres-ephemeral-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "direito_lux_staging"
        - name: DB_USER
          value: "direito_lux"
        - name: DB_PASSWORD
          value: "direito_lux_password"
        # Redis config
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        # RabbitMQ config
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        # App config
        - name: PORT
          value: "8080"
        - name: SERVER_PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        # JWT config
        - name: JWT_SECRET
          value: "direito-lux-jwt-secret-key-staging-2025"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_EXPIRATION_MINUTES
          value: "60"
        # Disable problematic features
        - name: PROMETHEUS_ENABLED
          value: "false"
        - name: JAEGER_ENABLED
          value: "false"
        - name: KEYCLOAK_ENABLED
          value: "false"
        # Keycloak config (required even when disabled)
        - name: KEYCLOAK_URL
          value: "http://keycloak:8080"
        - name: KEYCLOAK_REALM
          value: "direito-lux"
        - name: KEYCLOAK_CLIENT_ID
          value: "direito-lux-client"
        - name: KEYCLOAK_CLIENT_SECRET
          value: "fake-secret-disabled"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-fixed
  namespace: direito-lux-staging
spec:
  selector:
    app: auth-service-fixed
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service-fixed
  namespace: direito-lux-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-service-fixed
  template:
    metadata:
      labels:
        app: tenant-service-fixed
    spec:
      containers:
      - name: tenant-service
        image: us-central1-docker.pkg.dev/direito-lux-staging-2025/direito-lux-staging/tenant-service:latest
        ports:
        - containerPort: 8080
        env:
        # Database config
        - name: DB_HOST
          value: "postgres-ephemeral-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "direito_lux_staging"
        - name: DB_USER
          value: "direito_lux"
        - name: DB_PASSWORD
          value: "direito_lux_password"
        # Redis config
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        # RabbitMQ config
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        # App config
        - name: PORT
          value: "8080"
        - name: SERVER_PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        # Disable problematic features
        - name: PROMETHEUS_ENABLED
          value: "false"
        - name: JAEGER_ENABLED
          value: "false"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service-fixed
  namespace: direito-lux-staging
spec:
  selector:
    app: tenant-service-fixed
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP