# SOLUÇÃO SIMPLIFICADA - Serviços Mínimos Funcionais
# Remove dependências problemáticas para funcionar imediatamente

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-simple
  namespace: direito-lux-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-simple
  template:
    metadata:
      labels:
        app: auth-service-simple
    spec:
      containers:
      - name: auth-service
        image: us-central1-docker.pkg.dev/direito-lux-staging-2025/direito-lux-staging/auth-service:latest
        ports:
        - containerPort: 8080
        env:
        # Configuração mínima - sem DB externo
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        # App config
        - name: PORT
          value: "8080"
        - name: SERVER_PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        # JWT config
        - name: JWT_SECRET
          value: "direito-lux-jwt-secret-key-staging-2025"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_EXPIRATION_MINUTES
          value: "60"
        # Disable all external dependencies
        - name: PROMETHEUS_ENABLED
          value: "false"
        - name: JAEGER_ENABLED
          value: "false"
        - name: KEYCLOAK_ENABLED
          value: "false"
        - name: DATABASE_ENABLED
          value: "false"
        - name: RABBITMQ_ENABLED
          value: "false"
        - name: REDIS_ENABLED
          value: "false"
        # RabbitMQ (fake values - required even when disabled)
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@localhost:5672/"
        - name: RABBITMQ_HOST
          value: "localhost"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        # Redis (fake values - required even when disabled)
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        # Keycloak (fake values)
        - name: KEYCLOAK_URL
          value: "http://localhost:8080"
        - name: KEYCLOAK_REALM
          value: "direito-lux"
        - name: KEYCLOAK_CLIENT_ID
          value: "direito-lux-client"
        - name: KEYCLOAK_CLIENT_SECRET
          value: "fake-secret"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-simple
  namespace: direito-lux-staging
spec:
  selector:
    app: auth-service-simple
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service-simple
  namespace: direito-lux-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-service-simple
  template:
    metadata:
      labels:
        app: tenant-service-simple
    spec:
      containers:
      - name: tenant-service
        image: us-central1-docker.pkg.dev/direito-lux-staging-2025/direito-lux-staging/tenant-service:latest
        ports:
        - containerPort: 8080
        env:
        # Configuração mínima
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        # App config
        - name: PORT
          value: "8080"
        - name: SERVER_PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        # Disable all external dependencies
        - name: PROMETHEUS_ENABLED
          value: "false"
        - name: JAEGER_ENABLED
          value: "false"
        - name: DATABASE_ENABLED
          value: "false"
        - name: RABBITMQ_ENABLED
          value: "false"
        - name: REDIS_ENABLED
          value: "false"
        # RabbitMQ (fake values - required even when disabled)
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@localhost:5672/"
        - name: RABBITMQ_HOST
          value: "localhost"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        # Redis (fake values - required even when disabled)
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service-simple
  namespace: direito-lux-staging
spec:
  selector:
    app: tenant-service-simple
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP